version: '3.3'
services:
  wordpress:
    image: wordpress:latest
    ports:
       - 80:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    # volumes:
    #   - .:/var/www/html
  db:
    image: mysql
    restart: always
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
      - MYSQL_DATABASE=wordpress
    volumes:
      - db:/var/lib/mysql
volumes:
  wordpress:
  db:
