version: '3.3'
services:
  wordpress:
    build:
      context: .
      target: dev
    container_name: reactapp
    command: npm run start
    ports:
       - 80:3000
    restart: always
    volumes:
     - .:/app
      - /app/node_modules
